#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.1.8.1 2004/10/15 21:14:00 wchang0222%aol.com Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile-tlsu.com

DATAFILES +=

all:: $(FILES)
publish:: all pkg

include ../Makefile-tlsu.targ
