# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /mnt/Documents/kompozer/mozilla/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/usr/local/bin:/usr/bin:/bin:/usr/games/bin:.
MOZ_STANDALONE_COMPOSER=1
# --enable-optimize is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --disable-svg is used by configure (not client.mk)
# --without-system-mng is used by configure (not client.mk)
# --without-system-png is used by configure (not client.mk)
# --disable-ldap is used by configure (not client.mk)
# --disable-mailnews is used by configure (not client.mk)
# --disable-installer is used by configure (not client.mk)
# --disable-activex is used by configure (not client.mk)
# --disable-activex-scripting is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --disable-oji is used by configure (not client.mk)
# --disable-necko-disk-cache is used by configure (not client.mk)
# --enable-single-profile is used by configure (not client.mk)
# --disable-profilesharing is used by configure (not client.mk)
# --enable-extensions=wallet,xml-rpc,xmlextras,pref,universalchardet,spellcheck is used by configure (not client.mk)
# --enable-necko-protocols=http,ftp,file,jar,viewsource,res,data is used by configure (not client.mk)
# --disable-pedantic is used by configure (not client.mk)
# --disable-short-wchar is used by configure (not client.mk)
# --disable-xprint is used by configure (not client.mk)
# --enable-strip-libs is used by configure (not client.mk)
# --enable-crypto is used by configure (not client.mk)
# --disable-mathml is used by configure (not client.mk)
# --with-system-zlib is used by configure (not client.mk)
# --enable-toolkit=gtk2 is used by configure (not client.mk)
# --enable-default-toolkit=gtk2 is used by configure (not client.mk)
# --enable-xft is used by configure (not client.mk)
# --disable-freetype2 is used by configure (not client.mk)
# --enable-image-decoders=default,-xbm is used by configure (not client.mk)
