#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"$Id: Makefile,v 1.3.78.1 2004/10/15 21:13:59 wchang0222%aol.com Exp $"
#

CORE_DEPTH = ../../../..
include ../Makefile.com

DATAFILES +=

all:: $(FILES)
publish:: all pkg

include ../Makefile.targ
